<a href="https://colab.research.google.com/github/Pratik-sharma-py/datascience/blob/main/cleaning_pre_processing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/content/archive (6).zip")
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [4]:
clean_df = df.copy()
clean_df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31/12/2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31/12/2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31/12/2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31/12/2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31/12/2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [5]:
clean_df = clean_df.dropna()

In [44]:
main_column = ["order_id","order_date","ship_date","ship_mode","customer_name","segment","state","country","market","region","product_id","category","sub_category","product_name","sales","quantity","discount","profit"]

for col in main_column:
  clean_df[col] = clean_df[col].astype("string")
  clean_df[col] = clean_df[col].str.title()

clean_df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,Ag-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.14,35.46,Medium,2011
1,In-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,Apac,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.036,9.72,Medium,2011
2,Hu-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,Emea,Emea,...,Office Supplies,Storage,"Tenex Box, Single Width",66.0,4,0.0,29.64,8.17,High,2011
3,It-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,Eu,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45.0,3,0.5,-26.055,4.82,High,2011
4,In-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,Apac,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114.0,5,0.1,37.77,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Ca-2014-115427,31/12/2014,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,Us,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14.0,2,0.2,4.5188,0.89,Medium,2014
51286,Mo-2014-2560,31/12/2014,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4.0,1,0.0,0.42,0.49,Medium,2014
51287,Mx-2014-110527,31/12/2014,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,Latam,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26.0,3,0.0,12.36,0.35,Medium,2014
51288,Mx-2014-114783,31/12/2014,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,Latam,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7.0,1,0.0,0.56,0.20,Medium,2014
51289,Ca-2014-156720,31/12/2014,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,Us,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,0.17,Medium,2014

In [45]:
clean_df["order_id"] = clean_df["order_id"].astype("string")
clean_df["order_id"]

0           Ag-2011-2040
1          In-2011-47883
2           Hu-2011-1220
3        It-2011-3647632
4          In-2011-47883
              ...
51285     Ca-2014-115427
51286       Mo-2014-2560
51287     Mx-2014-110527
51288     Mx-2014-114783
51289     Ca-2014-156720
Name: order_id, Length: 51290, dtype: string

In [47]:
clean_df["order_date"] = pd.to_datetime(clean_df["order_date"], format="%d/%m/%Y")
clean_df["order_date"]

0       2011-01-01
1       2011-01-01
2       2011-01-01
3       2011-01-01
4       2011-01-01
           ...
51285   2014-12-31
51286   2014-12-31
51287   2014-12-31
51288   2014-12-31
51289   2014-12-31
Name: order_date, Length: 51290, dtype: datetime64[ns]

In [49]:
clean_df["ship_date"] = pd.to_datetime(clean_df["ship_date"], format="%d/%m/%Y")
clean_df["ship_date"]

0       2011-01-06
1       2011-01-08
2       2011-01-05
3       2011-01-05
4       2011-01-08
           ...
51285   2015-01-04
51286   2015-01-05
51287   2015-01-02
51288   2015-01-06
51289   2015-01-04
Name: ship_date, Length: 51290, dtype: datetime64[ns]

In [17]:

clean_df["ship_mode"] = clean_df["ship_mode"].astype("string")
clean_df["ship_mode"]

0        Standard Class
1        Standard Class
2          Second Class
3          Second Class
4        Standard Class
              ...
51285    Standard Class
51286    Standard Class
51287      Second Class
51288    Standard Class
51289    Standard Class
Name: ship_mode, Length: 51290, dtype: object

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [43]:
clean_df["customer_name"] = clean_df["customer_name"].astype("string")
clean_df["customer_name"]

0         Toby Braunhardt
1             Joseph Holt
2           Annie Thurman
3            Eugene Moren
4             Joseph Holt
               ...
51285          Erica Bern
51286           Liz Preis
51287    Charlotte Melton
51288       Tamara Dahlen
51289       Jill Matthias
Name: customer_name, Length: 51290, dtype: string

In [32]:
clean_df["segment"] = clean_df["segment"].astype(str)
#clean_df["segment"]

In [33]:
clean_df["state"] = clean_df["state"].astype(str)
#clean_df["state"]

In [34]:
clean_df["country"] = clean_df["country"].astype(str)
#clean_df["country"]

In [35]:
clean_df["market"] = clean_df["market"].astype(str)
#clean_df["market"]

In [36]:
clean_df["region"] = clean_df["region"].astype(str)
#clean_df["region"]

In [37]:
clean_df["product_id"] = clean_df["product_id"].astype(str)
#clean_df["product_id"]

In [38]:
clean_df["category"] = clean_df["category"].astype(str)
#clean_df["category"]

In [39]:
clean_df["sub_category"] = clean_df["sub_category"].astype(str)
#clean_df["sub_category"]

In [40]:
clean_df["product_name"] = clean_df["product_name"].astype(str)
#clean_df["product_name"]

In [41]:
clean_df["sales"] = clean_df["sales"].astype(str).str.replace(",", "").astype(float)
#clean_df["sales"]

In [52]:
clean_df["order_priority"] = clean_df["order_priority"].astype("string")
#clean_df["order_priority"]

In [53]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  string
 1   order_date      51290 non-null  datetime64[ns]
 2   ship_date       51290 non-null  datetime64[ns]
 3   ship_mode       51290 non-null  string
 4   customer_name   51290 non-null  string
 5   segment         51290 non-null  string
 6   state           51290 non-null  string
 7   country         51290 non-null  string
 8   market          51290 non-null  string
 9   region          51290 non-null  string
 10  product_id      51290 non-null  string
 11  category        51290 non-null  string
 12  sub_category    51290 non-null  string
 13  product_name    51290 non-null  string
 14  sales           51290 non-null  string
 15  quantity        51290 non-null  string
 16  discount        51290 non-null  string
 17  profit          51290 non-null  string
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  string
 20  year            51290 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(1), string(17)
memory usage: 8.2 MB

In [54]:
clean_df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64