<a href="https://colab.research.google.com/github/Pratik-sharma-py/datascience/blob/main/cleaning_project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/archive (9).zip")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

**from info() we can notice problems like:**


*   many columns are stored as object
*   durations are in minutes and seasons

*   some values are missing

In [ ]:
#we can also  calculate missing percentage
missing_percentage = (df.isnull().sum()/len(df)) * 100
missing_percentage

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [ ]:
#duplicated() returns True for rows that are duplicates.
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8802    False
8803    False
8804    False
8805    False
8806    False
Length: 8807, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

we got to know that there is no duplicate column.

In [ ]:
# unique() shows distinct values in a column.
df["type"].unique()

array(['Movie', 'TV Show'], dtype=object)

In [ ]:
df["country"].unique()

array(['United States', 'South Africa', nan, 'India',
       'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',
       'United Kingdom', 'Germany, Czech Republic', 'Mexico', 'Turkey',
       'Australia', 'United States, India, France', 'Finland',
       'China, Canada, United States',
       'South Africa, United States, Japan', 'Nigeria', 'Japan',
       'Spain, United States', 'France', 'Belgium',
       'United Kingdom, United States', 'United States, United Kingdom',
       'France, United States', 'South Korea', 'Spain',
       'United States, Singapore', 'United Kingdom, Australia, France',
       'United Kingdom, Australia, France, United States',
       'United States, Canada', 'Germany, United States',
       'South Africa, United States', 'United States, Mexico',
       'United States, Italy, France, Japan',
       'United States, Italy, Romania, United Kingdom',
       'Australia, United States', 'Argentina, Venezuela',
       'United States, United Kingdom, Canada', 'China, Hong Kong',
       'Russia', 'Canada', 'Hong Kong', 'United States, China, Hong Kong',
       'Italy, United States', 'United States, Germany',
       'United Kingdom, Canada, United States', ', South Korea',
       'Ireland', 'India, Nepal',
       'New Zealand, Australia, France, United States', 'Italy',
       'Italy, Brazil, Greece', 'Argentina', 'Jordan', 'Colombia',
       'United States, Japan', 'Belgium, United Kingdom',
       'Switzerland, United Kingdom, Australia', 'Israel, United States',
       'Canada, United States', 'Brazil', 'Argentina, Spain', 'Taiwan',
       'United States, Nigeria', 'Bulgaria, United States',
       'Spain, United Kingdom, United States', 'United States, China',
       'United States, France',
       'Spain, France, United Kingdom, United States',
       ', France, Algeria', 'Poland', 'Germany',
       'France, Israel, Germany, United States, United Kingdom',
       'New Zealand', 'Saudi Arabia', 'Thailand', 'Indonesia',
       'Egypt, Denmark, Germany', 'United States, Switzerland',
       'Hong Kong, Canada, United States', 'Kuwait, United States',
       'France, Canada, United States, Spain',
       'France, Netherlands, Singapore', 'France, Belgium',
       'Ireland, United States, United Kingdom', 'Egypt', 'Malaysia',
       'Israel', 'Australia, New Zealand', 'United Kingdom, Germany',
       'Belgium, Netherlands', 'South Korea, Czech Republic',
       'Australia, Germany', 'Vietnam', 'United Kingdom, Belgium',
       'United Kingdom, Australia, United States',
       'France, Japan, United States',
       'United Kingdom, Germany, Spain, United States',
       'United Kingdom, United States, France, Italy',
       'United States, Germany, Canada',
       'United States, France, Italy, United Kingdom',
       'United States, United Kingdom, Germany, Hungary',
       'United States, New Zealand', 'Sweden', 'China', 'Lebanon',
       'Romania', 'Finland, Germany', 'Lebanon, Syria', 'Philippines',
       'Iceland', 'Denmark', 'United States, India',
       'Philippines, Singapore, Indonesia',
       'China, United States, Canada', 'Lebanon, United Arab Emirates',
       'Canada, United States, Denmark', 'United Arab Emirates',
       'Mexico, France, Colombia', 'Netherlands',
       'Germany, United States, France', 'United States, Bulgaria',
       'United Kingdom, France, Germany, United States',
       'Norway, Denmark', 'Syria, France, Lebanon, Qatar',
       'United States, Czech Republic', 'Mauritius',
       'Canada, South Africa', 'Austria', 'Mexico, Brazil',
       'Germany, France', 'Mexico, United States',
       'United Kingdom, France, Spain, United States',
       'United States, Australia',
       'United States, United Kingdom, France', 'United States, Russia',
       'United States, United Kingdom, New Zealand',
       'Australia, United Kingdom', 'Canada, Nigeria, United States',
       'France, United States, United Kingdom, Canada',
       'France, United Kingdom', 'India, United Kingdom',
       'Canada, United States, Mexico',
       'United Kingdom, Germany, United States',
       'Czech Republic, United Kingdom, United States',
       'China, United Kingdom', 'Italy, United Kingdom', 'China, Taiwan',
       'United States, Brazil, Japan, Spain, India',
       'United States, China, United Kingdom', 'Cameroon',
       'Lebanon, Palestine, Denmark, Qatar', 'Japan, United States',
       'Uruguay, Germany', 'Egypt, Saudi Arabia',
       'United Kingdom, France, Poland, Germany, United States',
       'Ireland, Switzerland, United Kingdom, France, United States',
       'United Kingdom, South Africa, France',
       'Ireland, United Kingdom, France, Germany',
       'Russia, United States', 'United Kingdom, United States, France',
       'United Kingdom,', 'United States, India, United Kingdom', 'Kenya',
       'Spain, Argentina', 'India, United Kingdom, France, Qatar',
       'Belgium, France', 'Argentina, Chile', 'United States, Thailand',
       'Chile, Brazil', 'United States, Colombia',
       'Canada, United States, United Kingdom', 'Uruguay', 'Luxembourg',
       'United States, Cambodia, Romania', 'Bangladesh',
       'Spain, Belgium, United States',
       'United Kingdom, United States, Australia',
       'Canada, United States, France', 'Portugal, United States',
       'Portugal, Spain', 'India, United States',
       'United Kingdom, Ireland', 'United Kingdom, Spain, United States',
       'Hungary, United States', 'United States, South Korea',
       'Canada, United States, Cayman Islands', 'India, France',
       'France, Canada', 'Canada, Hungary, United States', 'Norway',
       'Canada, United Kingdom, United States',
       'United Kingdom, Germany, France, United States',
       'Denmark, United States', 'Senegal', 'France, Algeria',
       'United Kingdom, Finland, Germany, United States, Australia, Japan, France, Ireland',
       'Philippines, Canada, United Kingdom, United States',
       'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong',
       'Singapore', 'Kuwait', 'United States, France, Serbia',
       'United States, Italy', 'Spain, Italy',
       'United States, Ireland, United Kingdom, India',
       'United Kingdom, Singapore', 'Hong Kong, United States',
       'United States, Malta, France, United Kingdom',
       'United States, China, Canada', 'Canada, United States, Ireland',
       'Lebanon, Canada, France', 'Japan, Canada, United States',
       'Spain, France, Canada',
       'Denmark, Singapore, Canada, United States',
       'United States, France, Denmark', 'United States, China, Colombia',
       'Spain, Thailand, United States', 'Mexico, Spain',
       'Ireland, Luxembourg, Belgium', 'China, United States',
       'Canada, Belgium', 'Canada, United Kingdom',
       'Lebanon, United Arab Emirates, France, Switzerland, Germany',
       'France, Belgium, Italy',
       'Lebanon, United States, United Arab Emirates', 'Lebanon, France',
       'France, Lebanon', 'France, Lebanon, United Kingdom',
       'France, Norway, Lebanon, Belgium',
       'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands',
       'United States, United Kingdom, India', 'Indonesia, Netherlands',
       'Turkey, South Korea', 'Serbia, United States', 'Namibia',
       'United Kingdom, Kenya', 'United Kingdom, France, Germany, Spain',
       'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany',
       'Thailand, United States',
       'United States, France, Canada, Belgium', 'United Kingdom, China',
       'Germany, China, United Kingdom',
       'Australia, New Zealand, United States',
       'Hong Kong, Iceland, United States', 'France, Australia, Germany',
       'United States, Belgium, Canada, France', 'South Africa, Angola',
       'United States, Philippines',
       'United States, United Kingdom, Canada, China',
       'United States, Canada, United Kingdom', 'Turkey, United States',
       'Peru, Germany, Norway', 'Mozambique', 'Brazil, France',
       'China, Spain, South Korea, United States', 'Spain, Germany',
       'Hong Kong, China', 'France, Belgium, Luxembourg, Cambodia,',
       'United Kingdom, Australia', 'Belarus',
       'Indonesia, United Kingdom',
       'Switzerland, France, Belgium, United States', 'Ghana',
       'Spain, France, Canada, United States', 'Chile, Italy',
       'United Kingdom, Nigeria', 'Chile', 'France, Egypt',
       'Egypt, France', 'France, Brazil, Spain, Belgium',
       'Egypt, Algeria', 'Canada, South Korea, United States',
       'Nigeria, United Kingdom', 'United States, France, Canada',
       'Poland, United States',
       'United Arab Emirates, Jordan, Lebanon, Saudi Arabia',
       'United States, Mexico, Spain, Malta',
       'Saudi Arabia, United Arab Emirates', 'Zimbabwe',
       'United Kingdom, Germany, United Arab Emirates, New Zealand',
       'Romania, United States', 'Canada, Nigeria',
       'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States',
       'United Kingdom, Spain', 'Finland, France',
       'United Kingdom, Germany, United States, France',
       'India, United Kingdom, China, Canada, Japan, South Korea, United States',
       'Italy, United Kingdom, France', 'United States, Mexico, Colombia',
       'Turkey, India', 'Italy, Turkey',
       'United Kingdom, United States, Japan',
       'France, Belgium, United States',
       'Puerto Rico, United States, Colombia', 'Uruguay, Argentina',
       'United States, United Kingdom, Japan', 'United States, Argentina',
       'United Kingdom, Italy', 'Ireland, United Kingdom',
       'United Kingdom, France, Belgium, Canada, United States',
       'Netherlands, Germany, Denmark, United Kingdom', 'Hungary',
       'Austria, Germany', 'Taiwan, China',
       'United Kingdom, United States, Ireland',
       'South Korea, United States', 'Brazil, United Kingdom',
       'Pakistan, United States', 'Romania, France, Switzerland, Germany',
       'Romania, United Kingdom', 'France, Malta, United States',
       'Cyprus',
       'United Kingdom, France, Belgium, Ireland, United States',
       'United States, Norway, Canada', 'Kenya, United States',
       'France, South Korea, Japan, United States', 'Taiwan, Malaysia',
       'Uruguay, Argentina, Germany, Spain',
       'United States, United Kingdom, France, Germany, Japan',
       'United States, France, Japan',
       'United Kingdom, France, United States',
       'Spain, France, United States',
       'Indonesia, South Korea, Singapore', 'United States, Spain',
       'Netherlands, Germany, Italy, Canada',
       'Spain, Germany, Denmark, United States', 'Norway, Sweden',
       'South Korea, Canada, United States, China',
       'Argentina, Uruguay, Serbia', 'France, Japan',
       'Mauritius, South Africa', 'United States, Poland',
       'United Kingdom, United States, Germany, Denmark, Belgium, Japan',
       'India, Germany', 'India, United Kingdom, Canada, United States',
       'Philippines, United States', 'Romania, Bulgaria, Hungary',
       'Uruguay, Guatemala', 'France, Senegal, Belgium',
       'United Kingdom, Canada', 'Mexico, United States, Spain, Colombia',
       'Canada, Norway', 'Singapore, United States',
       'Finland, Germany, Belgium', 'United Kingdom, France',
       'United States, Chile', 'United Kingdom, Japan, United States',
       'Spain, United Kingdom', 'Argentina, United States, Mexico',
       'United States, South Korea, Japan', 'Canada, Australia',
       'United Kingdom, Hungary, Australia', 'Italy, Belgium',
       'United States, United Kingdom, Germany', 'Switzerland',
       'Singapore, Malaysia',
       'France, Belgium, Luxembourg, Romania, Canada, United States',
       'South Africa, Nigeria', 'Spain, France',
       'United Kingdom, Hong Kong', 'Pakistan', 'Brazil, United States',
       'Denmark, Brazil, France, Portugal, Sweden', 'India, Turkey',
       'Malaysia, Singapore, Hong Kong', 'Philippines, Singapore',
       'Australia, Canada', 'Taiwan, China, France, United States',
       'Germany, Italy', 'Colombia, Peru, United Kingdom',
       'Thailand, China, United States', 'Argentina, United States',
       'Sweden, United States', 'Uruguay, Spain, Mexico',
       'France, Luxembourg, Canada', 'Denmark, Spain', 'Chile, Argentina',
       'United Kingdom, Belgium, Sweden', 'Canada, Brazil',
       'Italy, France', 'Canada, Germany',
       'Pakistan, United Arab Emirates', 'Ghana, United States',
       'Mexico, Finland', 'United Arab Emirates, United Kingdom, India',
       'Netherlands, Belgium', 'United States, Taiwan',
       'Austria, Iraq, United States', 'United Kingdom, Malawi',
       'Paraguay, Argentina', 'United Kingdom, Russia, United States',
       'India, Pakistan', 'Indonesia, Singapore', 'Spain, Belgium',
       'Iceland, Sweden, Belgium', 'Croatia', 'Uruguay, Argentina, Spain',
       'United Kingdom, Ireland, United States',
       'Canada, Germany, France, United States', 'United Kingdom, Japan',
       'Norway, Denmark, Netherlands, Sweden',
       'Hong Kong, China, United States', 'Ireland, Canada',
       'Italy, Switzerland, France, Germany', 'Mexico, Netherlands',
       'United States, Sweden', 'Germany, France, Russia',
       'France, Iran, United States', 'United Kingdom, India',
       'Russia, Poland, Serbia', 'Spain, Portugal', 'Peru',
       'Mexico, Argentina',
       'United Kingdom, Canada, United States, Cayman Islands',
       'Indonesia, United States',
       'United States, Israel, United Kingdom, Canada',
       'Norway, Iceland, United States', 'Czech Republic, United States',
       'United Kingdom, India, United States',
       'United Kingdom, West Germany', 'India, Australia',
       'United States,', 'Belgium, United Kingdom, United States',
       'India, Germany, Austria',
       'United States, Brazil, South Korea, Mexico, Japan, Germany',
       'Spain, Mexico', 'China, Japan', 'Argentina, France',
       'China, United States, United Kingdom',
       'France, Luxembourg, United States',
       'China, United States, Australia', 'Colombia, Mexico',
       'United States, Canada, Ireland', 'Chile, Peru',
       'Argentina, Italy', 'Canada, Japan, United States',
       'United Kingdom, Canada, United States, Germany',
       'Italy, Switzerland, Albania, Poland',
       'United States, Japan, Canada', 'Cambodia',
       'Italy, United States, Argentina',
       'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait',
       'United States, Canada, Indonesia, United Kingdom, China, Singapore',
       'Spain, Colombia',
       'United Kingdom, South Africa, Australia, United States',
       'Bulgaria', 'Argentina, Brazil, France, Poland, Germany, Denmark',
       'United Kingdom, Spain, United States, Germany',
       'Philippines, Qatar', 'Netherlands, Belgium, Germany, Jordan',
       'United Arab Emirates, United States', 'Norway, Germany, Sweden',
       'South Korea, China', 'Georgia', 'Soviet Union, India',
       'Australia, United Arab Emirates', 'Canada, Germany, South Africa',
       'South Korea, China, United States', 'India, Soviet Union',
       'India, Mexico', 'Georgia, Germany, France',
       'United Arab Emirates, Romania', 'India, Malaysia',
       'Germany, Jordan, Netherlands', 'Turkey, France, Germany, Poland',
       'Greece, United States', 'France, United Kingdom, United States',
       'Norway, Germany', 'France, Morocco', 'Cambodia, United States',
       'United States, Denmark', 'United States, Colombia, Mexico',
       'United Kingdom, Italy, Israel, Peru, United States',
       'Argentina, Uruguay, Spain, France',
       'United Kingdom, France, United States, Belgium',
       'France, Canada, China, Cambodia',
       'United Kingdom, France, Belgium, United States', 'Chile, France',
       'Netherlands, United States', 'France, United Kingdom, India',
       'Czech Republic, Slovakia', 'Singapore, France',
       'Spain, Switzerland', 'United States, Australia, China',
       'South Africa, United States, Germany',
       'United States, United Kingdom, Australia',
       'Spain, Italy, Argentina', 'Chile, Spain, Argentina, Germany',
       'West Germany', 'Austria, Czech Republic', 'Lebanon, Qatar',
       'United Kingdom, Jordan, Qatar, Iran',
       'France, South Korea, Japan', 'Israel, Germany, France',
       'Canada, Japan, Netherlands', 'United States, Hungary',
       'France, Germany', 'France, Qatar',
       'United Kingdom, Germany, Canada', 'Ireland, South Africa',
       'Chile, United States, France', 'Belgium, France, Netherlands',
       'United Kingdom, Ukraine, United States',
       'Germany, Australia, France, China', 'Norway, United States',
       'United States, Bermuda, Ecuador',
       'United States, Hungary, Ireland, Canada',
       'United Kingdom, Egypt, United States',
       'United States, France, United Kingdom', 'Spain, Mexico, France',
       'United States, South Africa', 'Hong Kong, China, Singapore',
       'South Africa, China, United States', 'Denmark, France, Poland',
       'New Zealand, United Kingdom',
       'Netherlands, Denmark, South Africa', 'Iran, France',
       'United Kingdom, United States, France, Germany',
       'Australia, France', 'Ireland, United Kingdom, United States',
       'United Kingdom, France, Germany', 'Canada, Luxembourg',
       'Brazil, Netherlands, United States, Colombia, Austria, Germany',
       'France, Canada, Belgium', 'Canada, France',
       'Bulgaria, United States, Spain, Canada', 'Sweden, Netherlands',
       'France, United States, Mexico',
       'Australia, United Kingdom, United Arab Emirates, Canada',
       'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay',
       'India, Iran', 'France, Belgium, Spain',
       'Denmark, Sweden, Israel, United States', 'United States, Iceland',
       'United Kingdom, Russia',
       'United States, Israel, Italy, South Africa',
       'Netherlands, Denmark, France, Germany', 'South Korea, Japan',
       'United Kingdom, Pakistan', 'France, New Zealand',
       'United Kingdom, Czech Republic, United States, Germany, Bahamas',
       'China, Germany, India, United States', 'Germany, Sri Lanka',
       'United States, India, Bangladesh',
       'United States, Canada, France', 'Brazil, France, Germany',
       'Germany, United States, Hong Kong, Singapore',
       'France, Germany, Switzerland',
       'Germany, France, Luxembourg, United Kingdom, United States',
       'United Kingdom, Canada, Italy', 'Czech Republic, France',
       'Taiwan, Hong Kong, United States, China', 'Germany, Australia',
       'United Kingdom, Poland, United States', 'Denmark, Zimbabwe',
       'United Kingdom, South Africa',
       'Finland, Sweden, Norway, Latvia, Germany',
       'South Africa, United States, New Zealand, Canada',
       'United States, Italy, United Kingdom, Liechtenstein',
       'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom',
       'United States, Australia, Mexico',
       'United Kingdom, Czech Republic, Germany, United States',
       'France, China, Japan, United States',
       'United States, South Korea, China', 'Germany, Belgium',
       'Pakistan, Norway, United States',
       'United States, Canada, Belgium, United Kingdom', 'Venezuela',
       'Canada, France, Italy, Morocco, United States',
       'Canada, Spain, France', 'United States, Indonesia',
       'Spain, France, Italy',
       'United Arab Emirates, United States, United Kingdom',
       'United Kingdom, Israel, Russia', 'Spain, Cuba',
       'United States, Brazil', 'United States, France, Mexico',
       'United States, Nicaragua',
       'United Kingdom, United States, Spain, Germany, Greece, Canada',
       'Italy, Canada, France',
       'United Kingdom, Denmark, Canada, Croatia', 'Italy, Germany',

#Check the Wrong data types

#Check Outliers

In [ ]:
df.describe(include="all")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s8807,Movie,Zubaan,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

#Lets Start cleaning the data

In [ ]:
# Make a copy so the original raw data stays unchanged.

clean_df = df.copy()

In [ ]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
main_columns = ["show_id","type","title","director","cast","country","date_added","release_year","rating","duration","listed_in","description"]
for col in main_columns:
  clean_df[col] = clean_df[col].astype("string").str.strip()

#clean_df

In [ ]:
clean_df["country"] = clean_df["country"].str.lower()
clean_df["country"]

0       united states
1        south africa
2                <NA>
3                <NA>
4               india
            ...
8802    united states
8803             <NA>
8804    united states
8805    united states
8806            india
Name: country, Length: 8807, dtype: string

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   string
 1   type          8807 non-null   string
 2   title         8807 non-null   string
 3   director      6173 non-null   string
 4   cast          7982 non-null   string
 5   country       7976 non-null   string
 6   date_added    8797 non-null   string
 7   release_year  8807 non-null   string
 8   rating        8803 non-null   string
 9   duration      8804 non-null   string
 10  listed_in     8807 non-null   string
 11  description   8807 non-null   string
dtypes: string(12)
memory usage: 825.8 KB

In [ ]:
clean_df.dtypes

show_id         string[python]
type            string[python]
title           string[python]
director        string[python]
cast            string[python]
country         string[python]
date_added      string[python]
release_year    string[python]
rating          string[python]
duration        string[python]
listed_in       string[python]
description     string[python]
dtype: object

In [ ]:
# Fix 1: Convert date to real datetime
clean_df['date_added'] = pd.to_datetime(
    clean_df['date_added'], errors='coerce')

clean_df['year_added'] = clean_df['date_added'].dt.year
clean_df['month_added'] = clean_df['date_added'].dt.month

clean_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,<NA>,united states,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,<NA>,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",<NA>,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,<NA>,<NA>,<NA>,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,<NA>,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0

In [ ]:
# Fix 2: Fill missing text fields
clean_df['director'] = clean_df['director'].fillna('Unknown')
clean_df['cast'] = clean_df['cast'].fillna('Unknown')
clean_df['country'] = clean_df['country'].fillna('Unknown')
clean_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,united states,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",united states,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019.0,11.0
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019.0,7.0
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",united states,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019.0,11.0
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",united states,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0,1.0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",india,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0

In [ ]:
# Fix 3: Remove dirty values from rating
bad_ratings = ['74 min', '84 min', '66 min']
clean_df.loc[clean_df['rating'].isin(bad_ratings), 'rating'] = None

clean_df['rating'] = clean_df['rating'].fillna('Unknown')
clean_df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,united states,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",south africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",india,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",united states,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019.0,11.0
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019.0,7.0
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",united states,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019.0,11.0
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",united states,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0,1.0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",india,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0

In [ ]:
# Fix 4: Separate numeric duration for movies
# 90 min = 90 (number)     2 Seasons  = 2 (number)
movie_mask = clean_df['type'] == 'Movie'
show_mask  = clean_df['type'] == 'TV Show'

clean_df.loc[movie_mask, 'duration_mins'] = (
    clean_df.loc[movie_mask, 'duration'].str.extract(r'(\d+)')[0].astype(float)
)
clean_df.loc[show_mask, 'duration_seasons'] = (
    clean_df.loc[show_mask, 'duration'].str.extract(r'(\d+)')[0].astype(float)
)

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           8807 non-null   string
 1   type              8807 non-null   string
 2   title             8807 non-null   string
 3   director          8807 non-null   string
 4   cast              8807 non-null   string
 5   country           8807 non-null   string
 6   date_added        8797 non-null   datetime64[ns]
 7   release_year      8807 non-null   string
 8   rating            8807 non-null   string
 9   duration          8804 non-null   string
 10  listed_in         8807 non-null   string
 11  description       8807 non-null   string
 12  year_added        8797 non-null   float64
 13  month_added       8797 non-null   float64
 14  duration_mins     6128 non-null   float64
 15  duration_seasons  2676 non-null   float64
dtypes: datetime64[ns](1), float64(4), string(11)
memory usage: 1.1 MB